In [1]:
import numpy as np
import pandas as pd
from warnings import filterwarnings
filterwarnings('ignore')
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
sun_data = pd.read_csv("../data/train/train.csv")
sun_data.drop(['Day', 'Hour','Minute'], axis='columns', inplace=True)
sun_data.tail()
sun_data.shape

DHI  DNI   WS     RH  T  TARGET
52555    0    0  2.4  70.70 -4     0.0
52556    0    0  2.4  66.79 -4     0.0
52557    0    0  2.2  66.78 -4     0.0
52558    0    0  2.1  67.72 -4     0.0
52559    0    0  2.1  67.70 -4     0.0

(52560, 6)

In [5]:
sun_data.shape

(52560, 6)

In [6]:
def create_data(data):
    data_X, data_Y = [], []
#     input_data_X, input_data_Y = [], []
    data_X = np.array(sun_data.loc[:, ["DHI", "DNI", "WS", "RH", "T"]].values)
    data_Y = np.array(sun_data.loc[:, ["TARGET"]].values)
#     for i in range(1092//7):
#         input_data_X += data_X[i*(48*7) : (i+1)*(48*7)]
#         input_data_Y += data_Y[i*(48*7) : (i+1)*(48*7)]
    return data_X, data_Y
#     return input_data_X, input_data_Y

X, Y = create_data(sun_data)
X[:10], Y[:10]

(array([[  0.  ,   0.  ,   1.5 ,  69.08, -12.  ],
        [  0.  ,   0.  ,   1.5 ,  69.06, -12.  ],
        [  0.  ,   0.  ,   1.6 ,  71.78, -12.  ],
        [  0.  ,   0.  ,   1.6 ,  71.75, -12.  ],
        [  0.  ,   0.  ,   1.6 ,  75.2 , -12.  ],
        [  0.  ,   0.  ,   1.5 ,  69.29, -11.  ],
        [  0.  ,   0.  ,   1.5 ,  72.56, -11.  ],
        [  0.  ,   0.  ,   1.4 ,  72.55, -11.  ],
        [  0.  ,   0.  ,   1.3 ,  74.62, -11.  ],
        [  0.  ,   0.  ,   1.3 ,  74.61, -11.  ]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]))

In [7]:
type(X)

numpy.ndarray

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

# scaler = StandardScaler()
# input_scaler = scaler.fit(X)
# output_scaler = scaler.fit(Y)
# X = input_scaler.transform(X)
# Y = output_scaler.transform(Y)

scaler = MinMaxScaler(feature_range = (0, 1))
input_scaler = scaler.fit(X)
output_scaler = scaler.fit(Y)
X = input_scaler.transform(X)
Y = output_scaler.transform(Y)

# X = X.reshape(-1,336,5)
# Y = Y.reshape(-1,7,1)
X[0], Y[0]

(array([ 0.        ,  0.        ,  0.01501292,  0.69139502, -0.12010336]),
 array([0.]))